on: push
name: Test
jobs:
  checks:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Test
        uses: cedrickring/golang-action/go1.14@1.5.2
        with:
          args: go test -race -coverprofile=coverage.txt -covermode=atomic
        env:
          GO111MODULE: "on"

      - name: Upload coverage
        uses: codecov/codecov-action@v1
